# render.yaml
# 正確的 Render Blueprint 配置

services:
  - type: web
    name: honeycomb-api
    env: python
    plan: starter # 或者您正在使用的方案
    
    # 告訴 Render 如何安裝依賴項
    buildCommand: "pip install -r requirements.txt"
    
    # 這是最關鍵的一行：告訴 Render 如何啟動您的應用
    # uvicorn api.index:app 的意思是：
    # "使用 uvicorn，去執行 api/index.py 這個模組 (api.index)，並找到名為 app 的 FastAPI 實例"
    startCommand: "uvicorn api.index:app --host 0.0.0.0 --port 10000"
    
    # 確保 Render 知道您的環境變數（如果有的話）
    # envVars:
    #   - key: PYTHON_VERSION
    #     value: 3.9 # 請根據您的需要調整

    # --- 新增此區塊 ---
    envVars:
      - key: SUPABASE_URL
        fromService:
          type: external # 或直接 sync from your environment group
          name: supabase-credentials # 這是您在 Render 建立的環境群組名稱
          key: SUPABASE_URL
      - key: SUPABASE_SERVICE_ROLE_KEY
        fromService:
          type: external
          name: supabase-credentials
          key: SUPABASE_SERVICE_ROLE_KEY
